### ISSUE TITLE
code refactoring

### ISSUE THREAD

**Issue by bellaj** [madiha95/Smart-Lock-Pi#1]
au lieu d'avoir différents bouts de code, met en place un seul projet ou tu définit chaque partie comme une differente fonction.
exp 1: 
insert_to_database()
send_cmd_to_arduino()
...

 ou bien définit les comme des modules dans ton projet et appel les via des include.

**Comment by madiha95** [comment]
Bonjour,
Je comprends je vais le faire ce soir inchallah merci.
Mer i

Le dim. 8 avr. 2018 à 13:19, Badr bellaj <notifications@github.com> a
écrit :
